version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: grpc_postgres
    restart: always
    environment:
      POSTGRES_USER: grpcuser
      POSTGRES_PASSWORD: grpcpass
      POSTGRES_DB: grpcdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
